export const ProductsDB = [
    {
        id: 1,
        url: "https://images-na.ssl-images-amazon.com/images/I/41gr0fllE9L._SX327_BO1,204,203,200_.jpg",
        name: "The Ride of a Lifetime",
        author: "Robert Iger",
        category: "Autobiographies",
        price: 157,
    },
    {
        id: 2,
        url: "https://images-na.ssl-images-amazon.com/images/I/41kWOyfqI9L._SX322_BO1,204,203,200_.jpg",
        name: "Can't Hurt Me",
        author: "David Goggins",
        category: "Audiobook",
        price: 836,
    },
    {
        id: 3,
        url: "https://images-na.ssl-images-amazon.com/images/I/41GmjqDIHmL._SX326_BO1,204,203,200_.jpg",
        name: "The Autobiography of Benjamin Franklin",
        author: "Benjamin Franklin",
        category: "Autobiographies",
        price: 207
    },
    {
        id: 4,
        url: "https://images-eu.ssl-images-amazon.com/images/I/51Ql68PA1UL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        name: "Mahatma Gandhi Autobiography: The Story Of My Experiments With Truth",
        author: "Mahatma Gandhi",
        category: "Autobiographies",
        price: 99,
    },
    {
        id: 5,
        url: "https://images-na.ssl-images-amazon.com/images/I/51I-QgidWHL._SX322_BO1,204,203,200_.jpg",
        name: "Elon Musk: How the Billionaire CEO of SpaceX and Tesla is Shaping our Future",
        author: "Ashlee Vance",
        category: "Autobiographies",
        price: 584,
    },
    {
        id: 6,
        url: "https://images-na.ssl-images-amazon.com/images/I/41n1edvVlLL._SX317_BO1,204,203,200_.jpg",
        name: "Steve Jobs: The Exclusive Biography",
        author: "Walter Isaacson",
        category: "Biography",
        price: 375,
    },
    {
        id: 7,
        url: "https://m.media-amazon.com/images/I/51N0TVAaaIL.jpg",
        name: "How I Braved Anu Aunty & Co-Founded A Million Dollar Company",
        author: "Varun Agarwal",
        category: "Biography",
        price: 130,
    },
    {
        id: 8,
        url: "https://images-na.ssl-images-amazon.com/images/I/51wbVQTpTgL._SX339_BO1,204,203,200_.jpg",
        name: "Wings of Fire: An Autobiography of Abdul Kalam",
        author: "A. P. J. Abdul Kalam",
        category: "AutoBiographies",
        price: 261,
    },
    {
        id: 9,
        url: "https://images-na.ssl-images-amazon.com/images/I/51XvWXNGR5L._SX325_BO1,204,203,200_.jpg",
        name: "Leonardo da Vinci",
        author: "Walter Isaacson",
        category: "Biography",
        price: 999,
    },
    {
        id: 10,
        url: "https://images-na.ssl-images-amazon.com/images/I/41L5qgUW2fL._SX327_BO1,204,203,200_.jpg",
        name: "A Promised Land",
        author: "Barack Obama",
        category: "Audiobook",
        price: 1708,
    },
    {
        id: 11,
        url: "https://images-na.ssl-images-amazon.com/images/I/41sEB1SxefL._SX307_BO1,204,203,200_.jpg",
        name: "Autobiography of a Yogi",
        author: "Paramahansa Yogananda",
        category: "Audiobook",
        price: 1126,
    },
    {
        id: 12,
        url: "https://images-na.ssl-images-amazon.com/images/I/51RHxkOx-7L._SX324_BO1,204,203,200_.jpg",
        name: "Surely you're Joking Mr Feynman: Adventures of a Curious Character",
        author: "Richard P Feynman",
        category: "Autobiographies",
        price: 381,
    },
    {
        id: 13,
        url: "https://images-na.ssl-images-amazon.com/images/I/51AtkUsQxDL._SX324_BO1,204,203,200_.jpg",
        name: "Turning Points : A Journey Through Challenges",
        author: "A. P. J. Abdul Kalam",
        category: "Autobiographies",
        price: 158,
    },
    {
        id: 14,
        url: "https://images-na.ssl-images-amazon.com/images/I/51+ZgolTkaL._SX326_BO1,204,203,200_.jpg",
        name: "Three Thousand Stitches: Ordinary People, Extraordinary Lives ",
        author: "Sudha Murty",
        category: "Autobiographies",
        price: 158,
    }
]